apiVersion: v1
kind: Service
metadata:
  name: {{ include "token-tally.fullname" . }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.privateLink.enabled }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "token-tally.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
