name = "token-tally-gateway"
main = "src/index.ts"
compatibility_date = "2024-05-01"

[[kv_namespaces]]
binding = "KEY_LIMITS"
id = "key_limits_us"

[env.europe]
data_location = "eu"
kv_namespaces = [{ binding = "KEY_LIMITS", id = "key_limits_eu" }]

[env.apac]
data_location = "apac"
kv_namespaces = [{ binding = "KEY_LIMITS", id = "key_limits_apac" }]
